# Generated by Django 4.2.1 on 2023-06-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creation_at',
            field=models.DateField(verbose_name='Дата добавления'),
        ),
    ]
